### ISSUE TITLE
Implement

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly-templates-ionic#1]
Would love to get this implemented!

**Comment by kentcdodds** [comment]
Referencing [original issue](https://github.com/formly-js/angular-formly/issues/51)

**Comment by mhartington** [comment]
Hey @kentcdodds let me know what needs to be done. Would love to be able to help out on this.
Cheers

**Comment by kentcdodds** [comment]
Cheers indeed :smiley:

My first question would be, have you ever used/heard of angular-formly before? If not, I'd be happy to give you a crash course sometime via hangouts on the capabilities and possibilities.

**Comment by timothynott** [comment]
We implemented something close to what you're asking for a couple weeks ago. Could probably be reworked for general consumption.

**Comment by kentcdodds** [comment]
Cool @timothynott! Would love your input. If you are both in, we could schedule a hangout and I can give you a rundown on all the things formly is capable of. The templates is the easy part :-)

**Comment by mhartington** [comment]
Sounds good to me. 

Feel free to shoot me an email 

mike at drifty dot com

Mike Hartington

**Comment by timothynott** [comment]
Tim at MobileIgniter dot com

On Sun, Feb 8, 2015 at 5:59 PM -0800, "Mike Hartington" notifications@github.com wrote:

Sounds good to me. 

Feel free to shoot me an email 

mike at drifty dot com

Mike Hartington
