### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mhartington** [formly-js/angular-formly-templates-ionic#14]
There should some documentation similar to what all the other templates have. Looking for someone who's never contributed to a project before to make this happen. 

Good example of what I mean is 
https://github.com/formly-js/angular-formly-templates-foundation
https://github.com/formly-js/angular-formly-templates-bootstrap

Just a small section about how to use each field and options that can be passed.

**Comment by kinggolf** [comment]
Hi Mike, Thanks for quick update to ion-radio template file. I would be willing to help with the documentation. I have not contributed to a project previously. Should I just start with README.md file?

**Comment by mhartington** [comment]
Awesome! Yeah the readme should be a good place to start. Eventually I want to do the same for the site and automate a changelog, but that's down the road. 

Mike Hartington

**Comment by kinggolf** [comment]
OK. I have quite a bit going on the next 1-2 weeks, but will squeeze it in. Should not take too much time. - Larry

**Comment by mhartington** [comment]
Documentation add via 5fb8e4f4f155f98c5b390471da1b2ecf2568b105
