### ISSUE TITLE
Adding "rows" to textarea element?

### ISSUE THREAD

**Issue by aaronksaunders** [formly-js/angular-formly-templates-ionic#16]
Not really sure how this library works, trying to adds additional functionality to input types... this works

``` Javascript
$templateCache.put("fields/ion-textarea.html","<label class=\"item item-input\"><textarea placeholder=\"{{options.templateOptions.placeholder}}\"  rows=\"{{options.templateOptions.rows}}\" ng-model=\"model[options.key]\"></textarea></label>");
```

but not sure of that is the correct approach?

**Comment by kentcdodds** [comment]
I would recommend against this approach. I recommend you take a look at
custom types and the extends option.

Extends example:
http://angular-formly.com/#/example/custom-types/extending-types
Learn angular-formly basics: http://learn.angular-formly.com
- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by mhartington** [comment]
Will add rows to text-area in the next release

**Comment by aaronksaunders** [comment]
@kentcdodds thanks for the links,  I will use the extending-types for another UI element, but was looking for an example that shows how to access the parent scope when in the `onKeypress` callback.

@mhartington any idea when the next release will be or should I move forward with my hack? no rush just wondering... and thanks for the quick response

**Comment by mhartington** [comment]
I can do it in a few hours. On a train heading home ATM. 

Mike Hartington

**Comment by aaronksaunders** [comment]
@mhartington no worries enjoy the trip home, and the long weekend, I will take a look at the final result so maybe next time I can just do it myself and submit a PR

**Comment by mhartington** [comment]
Awesome. I'd take a look at ion-radio's icon attribute. Textareas should have a default value if nothing is passed in

Mike Hartington

**Comment by mhartington** [comment]
Should be good now @aaronksaunders, let me know if there are any issues.
