### ISSUE TITLE
input icons

### ISSUE THREAD

**Issue by Evanion** [formly-js/angular-formly-templates-ionic#19]
Hello
I'm missing the ability to include [input icons](http://ionicframework.com/docs/components/#input-icons) in the fields.

I might work on it myself tomorrow, and send a PR.

**Comment by mhartington** [comment]
Sweet, I'll let you work out a PR for this. 

Might want to take a look at the [range input](https://github.com/formly-js/angular-formly-templates-ionic/blob/master/src/fields/ion-range.html) for conditional icons

**Comment by Evanion** [comment]
My fingers couldn't wait for tomorrow ;)
