### ISSUE TITLE
Don't use recursive packaging

### ISSUE THREAD

**Issue by ChALkeR** [formly-js/angular-formly-templates-ionic#29]
o_O O_o
1. `angular-formly-templates-ionic` 1.2.0 includes an `examples` dir.
2. Those examples also include `angular-formly-templates-ionic` itself in the `www/lib` dir.
3. Those copies also include an `examples` dir.
4. …
5. The total unpacked size is 215.8 MiB.

`examples` dirs:

```
./angular-formly-templates-ionic/examples
./angular-formly-templates-ionic/examples/stackedLabels/www/lib/angular-formly-templates-ionic/examples
./angular-formly-templates-ionic/examples/floatingLabels/www/lib/angular-formly-templates-ionic/examples
./angular-formly-templates-ionic/examples/inlineLabels/www/lib/angular-formly-templates-ionic/examples
./angular-formly-templates-ionic/examples/inlineLabels/www/lib/angular-formly-templates-ionic/examples/stackedLabels/www/lib/angular-formly-templates-ionic/examples
./angular-formly-templates-ionic/examples/inlineLabels/www/lib/angular-formly-templates-ionic/examples/floatingLabels/www/lib/angular-formly-templates-ionic/examples
```

`angular-formly-templates-ionic` copies:

```
./angular-formly-templates-ionic/
./angular-formly-templates-ionic/examples/stackedLabels/www/lib/angular-formly-templates-ionic
./angular-formly-templates-ionic/examples/floatingLabels/www/lib/angular-formly-templates-ionic
./angular-formly-templates-ionic/examples/inlineLabels/www/lib/angular-formly-templates-ionic
./angular-formly-templates-ionic/examples/inlineLabels/www/lib/angular-formly-templates-ionic/examples/stackedLabels/www/lib/angular-formly-templates-ionic
./angular-formly-templates-ionic/examples/inlineLabels/www/lib/angular-formly-templates-ionic/examples/floatingLabels/www/lib/angular-formly-templates-ionic
```

**Comment by ChALkeR** [comment]
Removing the nested `examples/*/www/lib/angular-formly-templates-ionic/examples` directories decreases the unpacked size 4 times (by 163.2 MiB), from 215.8 MiB to 52.6 MiB.

**Comment by mhartington** [comment]
Are you using bower or npm? Bower ignores these examples directories and doesn't include them when you install the package. I'll add a npmignore though to exclude the examples for npm

**Comment by ChALkeR** [comment]
npm. And that's in your git.

**Comment by ChALkeR** [comment]
See https://github.com/formly-js/angular-formly-templates-ionic/tree/v1.2.0/examples/inlineLabels/www/lib/angular-formly-templates-ionic/examples/floatingLabels/www/lib/angular-formly-templates-ionic/examples/select/www/lib

**Comment by mhartington** [comment]
Right, but the examples are there for testing purposes and it's not really possible to ignore them when pushing a release. I can clean up those examples, but I keep them there for testing purposes.

**Comment by ChALkeR** [comment]
@mhartington Do they have to be nested and duplicated several times for testing purposes? This is one link: https://github.com/formly-js/angular-formly-templates-ionic/tree/v1.2.0/examples/inlineLabels/www/lib/angular-formly-templates-ionic/examples/floatingLabels/www/lib/angular-formly-templates-ionic/examples/select/www/lib

Ok then.

**Comment by mhartington** [comment]
No not really (was an early test to be honest). Like I said, I'll can clean up the examples and get rid of the nested code.

**Comment by ChALkeR** [comment]
Btw, they are still there in git.
What is the reason for keeping them, again?

**Comment by mhartington** [comment]
Yes I know. On my list of priorities, this one is low on it.
Most people are using some sort of package manager so I'm not expecting anyone to just download a zip from github. 

I will get to it when I have time.
