### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly-templates-ionic#3]
Let's get this awesome library on npm! Make sure to update the author and other info (to you) :-)

https://www.npmjs.com/package/angular-formly-templates-ionic

![screen shot 2015-02-28 at 2 32 04 pm](https://cloud.githubusercontent.com/assets/1500684/6428208/a8fc9af0-bf56-11e4-87ca-11659fc22214.png)

**Comment by mhartington** [comment]
ANNNND done.

https://www.npmjs.com/package/angular-formly-templates-ionic

**Comment by kentcdodds** [comment]
Nice! Though I would recommend that you change the `author` property to your name. You did all of this bro :-)
