### ISSUE TITLE
Please Brach to Version with Examples

### ISSUE THREAD

**Issue by movibe** [formly-js/angular-formly-templates-ionic#30]
Currently the project is too heavy for use only with the bower, it would be interesting to have a branch only for examples and leave the master with only the final version to include in the project

**Comment by kentcdodds** [comment]
Personally, I would prefer the examples to just be placed on the website
like all the others.

**Comment by mhartington** [comment]
Agreed, I need to do something with the example. I like the idea of an examples branch. 
@movibe if you're using npm or bower, the examples should ignored via

https://github.com/formly-js/angular-formly-templates-ionic/blob/master/.npmignore

and

https://github.com/formly-js/angular-formly-templates-ionic/blob/master/bower.json#L23

Though there less example, and more just ways for me to test things :grin: 
I'll add them to my `.gitignore` so they just stay with me
