### ISSUE TITLE
integrate with angular-wizard and angular-formly 

### ISSUE THREAD

**Issue by NayHaPal** [formly-js/angular-formly-templates-ionic#33]
problem it to  ingrate angular-formly-templates-ionic with angular-wizard 

see this link 
http://angular-formly.com/#/example/integrations/angular-wizard

its possible betwen angular-formly  and  angular-wizard !!

can i use this angular-wizard with angular-formly-templates-ionic ?   how if its possible?

thanks

**Comment by mhartington** [comment]
Could you provide a small demo of what you've tried?

**Comment by NayHaPal** [comment]
hello sir 

i just try to know if i can use   angular-wizard and angular-formly and ionic form ,

you already integrate between angular-formly and ionic template  form on angular-formly-templates-ionic and its very usefull !!
but i now just want to use a  angular-wizard on angular-formly-templates-ionic  ,I just a ask if its possible to use   angular-wizard  by follow this guide line in the link below
http://angular-formly.com/#/example/integrations/angular-wizard

thanks for your Interest

**Comment by NayHaPal** [comment]
finally its work fine ,, and we can make integration by install 
angular-wizard and angular-formly and ionic form , angular-formly and then include all that to your angular module and then follow this guide line and its work perfect 
http://angular-formly.com/#/example/integrations/angular-wizard
thanks
