### ISSUE TITLE
Bower angular 1.2 depency

### ISSUE THREAD

**Issue by piernik** [formly-js/angular-formly-templates-ionic#4]
Can You increase angular depency to 1.3?

**Comment by kentcdodds** [comment]
@mhartington, we should probably have the same angular version as the core library in [bower.json](https://github.com/formly-js/angular-formly/blob/master/bower.json#L43) and in [package.json](https://github.com/formly-js/angular-formly/blob/master/package.json#L40)

**Comment by mhartington** [comment]
Have it fixed locally, but the recent GH issues are preventing me from pushing :disappointed: 
Will fix ASAP

**Comment by kentcdodds** [comment]
would be good to update the angular-formly dependency as well. Based on the templates, I think you need ">= 3.0.0"

**Comment by mhartington** [comment]
https://github.com/formly-js/angular-formly-templates-ionic/pull/6 should address this
