### ISSUE TITLE
Templatecache urls wrong?

### ISSUE THREAD

**Issue by fifafu** [formly-js/angular-formly-templates-ionic#8]
Hi,

I was trying to use the ionic angular formly templates, however I encountered an issue.
When using the distribution version which includes the templates via templateCache, I always get 404 not found errors for the templates.

Looking at the Code I think the getFieldTemplateUrl function should not include the "fields" in the url OR the templateCache.put should include the fields part too. (Look at https://github.com/formly-js/angular-formly-templates-ionic/blob/master/dist/angular-formly-templates-ionic.js )

For example it should be:

 $templateCache.put("fields/ion-input.html",...)

Best,
Andreas

**Comment by mhartington** [comment]
Thanks, missed that in reworking the build with gulp

**Comment by fifafu** [comment]
Hey,

I think now the bower.json is broken, there should be no "," after angular-formly 
(see https://raw.githubusercontent.com/formly-js/angular-formly-templates-ionic/master/bower.json#)
